// Temporary test route uses the real question input components. No live writes.
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const {spawn}=require('node:child_process');
const {chromium}=require('/private/tmp/hsk-community-tools/node_modules/playwright');
const root=path.resolve('src/app/yct-verification');assert(!fs.existsSync(root),'Refuse to replace an existing route');
const payload=JSON.parse(fs.readFileSync('supabase/library/yct-workbooks.json'));const qs=payload.lessons.flatMap(l=>l.questions.map(q=>({...q,level:l.level})));const choose=f=>qs.find(f);
const samples=[choose(q=>q.type==='multiple_choice'),choose(q=>q.type==='pinyin_choice'),choose(q=>q.type==='multi_matching'&&q.content.columns.some(c=>c.images)),choose(q=>q.type==='matching'&&q.content.left_tts),choose(q=>q.content.response_mode==='drawing'),choose(q=>q.content.response_mode==='oral'),choose(q=>q.content.response_mode==='ordering')].map((q,i)=>{const {answer,...publicQ}=q;return {...publicQ,id:'test-'+i,tags:[],lesson_id:null,lesson:null,created_at:''};});
fs.mkdirSync(root);fs.writeFileSync(path.join(root,'page.tsx'),`"use client"; // GENERATED YCT BROWSER VERIFICATION ONLY\nimport {useState} from 'react';import {QuestionInput} from '@/components/question-player-input';import {QuestionPinyinContext} from '@/components/question-visuals';import {pinyinAllowed} from '@/lib/question-pinyin';import type {QuestionRow,QuestionAnswer} from '@/lib/db-content';\nconst qs=${JSON.stringify(samples)} as unknown as QuestionRow[];\nexport default function Page(){const[show,setShow]=useState(true);const[answers,setAnswers]=useState<Record<string,QuestionAnswer>>({});return <main className="mx-auto max-w-3xl space-y-4 p-4"><button data-testid="toggle" onClick={()=>setShow(!show)}>{show?'Ẩn phiên âm':'Hiện phiên âm'}</button>{qs.map((q,i)=><section key={q.id} data-testid={'q'+i} className="rounded-xl border p-3"><QuestionPinyinContext.Provider value={{show:show&&pinyinAllowed(q)}}><QuestionInput question={q} value={answers[q.id]} onChange={v=>setAnswers({...answers,[q.id]:v})}/></QuestionPinyinContext.Provider><output data-testid={'answer'+i}>{typeof answers[q.id]==='string'&&String(answers[q.id]).startsWith('data:')?'MEDIA':JSON.stringify(answers[q.id])}</output></section>)}</main>}`);
let server,browser;const logs=[];
(async()=>{
 server=spawn('npm',['run','dev','--','--hostname','127.0.0.1','--port','3107'],{stdio:['ignore','pipe','pipe']});server.stdout.on('data',d=>logs.push(String(d)));server.stderr.on('data',d=>logs.push(String(d)));
 let ready=false;for(let i=0;i<80;i++){try{const r=await fetch('http://127.0.0.1:3107/yct-verification');if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert(ready,logs.join(''));
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/storage/v1/object/public/workbook-images/**',route=>{const filename=path.basename(new URL(route.request().url()).pathname);route.fulfill({body:fs.readFileSync(path.resolve('tools/yct-import/work/assets',filename)),contentType:'image/webp',headers:{'Access-Control-Allow-Origin':'*'}});});
 await page.goto('http://127.0.0.1:3107/yct-verification');await page.getByTestId('q0').waitFor();
 await page.waitForFunction(()=>document.querySelectorAll('[data-testid="q0"] ruby').length>0);assert.equal(await page.getByTestId('q1').locator('ruby').count(),0);assert.equal(await page.getByTestId('q2').locator('ruby').count(),0);
 assert.equal(await page.getByTestId('q1').locator('button:has(svg)').count(),0,'Pinyin choice must not expose the pronunciation');
 await page.getByTestId('toggle').click();assert.equal(await page.locator('ruby').count(),0);await page.getByTestId('toggle').click();assert(await page.getByTestId('q0').locator('ruby').count()>0);
 assert.equal(await page.getByTestId('q2').locator('img').count(),samples[2].content.columns[1].images.length);
 await page.getByTestId('q2').locator('select').first().selectOption('a');await page.getByTestId('q2').locator('select').nth(1).selectOption('b');assert.match(await page.getByTestId('answer2').textContent(),/0:1/);
 assert.equal(await page.getByTestId('q3').getByRole('button',{name:'Nghe mục 1',exact:true}).count(),1);assert.equal(await page.getByTestId('q3').locator('ruby').count(),0);
 const canvas=page.getByTestId('q4').locator('canvas');await canvas.scrollIntoViewIfNeeded();await page.waitForTimeout(800);const box=await canvas.boundingBox();await page.mouse.move(box.x+box.width*.4,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.6,{steps:10});await page.mouse.up();await page.waitForFunction(()=>document.querySelector('[data-testid="answer4"]').textContent==='MEDIA');
 await page.getByTestId('q5').locator('input[type=file]').setInputFiles({name:'speaking.webm',mimeType:'audio/webm',buffer:Buffer.from('audio fixture')});await page.waitForFunction(()=>document.querySelector('[data-testid="answer5"]').textContent==='MEDIA');assert.equal(await page.getByTestId('q5').locator('audio').count(),1);
 const order=page.getByTestId('q6');for(let i=0;i<samples[6].content.tokens.length;i++)await order.getByRole('button').last().click();assert.equal(JSON.parse(JSON.parse(await page.getByTestId('answer6').textContent())).length,samples[6].content.tokens.length);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile overflow');await page.screenshot({path:'tools/yct-import/work/browser-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Desktop overflow');assert.deepEqual(errors,[]);
 fs.writeFileSync('tools/yct-import/browser-report.json',JSON.stringify({passed:true,viewports:[390,1280],checks:['Pinyin default and toggle','No Pinyin on answer-revealing questions','Image legend rendered once','Matching answer selection','Listening labels remain hidden','Drawing response saved','Audio response preview','Paragraph ordering','No horizontal overflow','No browser exceptions']},null,2)+'\n');console.log('PASS: YCT question interactions at 390px and 1280px; no browser errors');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.kill('SIGTERM');const file=path.join(root,'page.tsx');if(fs.existsSync(file)&&fs.readFileSync(file,'utf8').includes('GENERATED YCT BROWSER VERIFICATION ONLY')){fs.unlinkSync(file);fs.rmdirSync(root);}});
